version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: pg-repairflow-dev
    environment:
      POSTGRES_USER: repairflow
      POSTGRES_PASSWORD: repairflow
      POSTGRES_DB: repairflow
    ports:
      - "5435:5432"
    volumes:
      - pgdata-dev:/var/lib/postgresql/data

volumes:
  pgdata-dev:
