version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: pg-repairflow-local
    environment:
      POSTGRES_USER: repairflow
      POSTGRES_PASSWORD: repairflow
      POSTGRES_DB: repairflow
    ports:
      - "5435:5432"
    volumes:
      - pgdata-local:/var/lib/postgresql/data

  backend:
    build: .
    container_name: api-repairflow-local
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/repairflow
      SPRING_DATASOURCE_USERNAME: repairflow
      SPRING_DATASOURCE_PASSWORD: repairflow

      APP_JWT_SECRET: "local-dev-secret-change-me"
      APP_JWT_EXP_MINUTES: "60"
      APP_UPLOAD_DIR: "uploads"

      CORS_ALLOWED_ORIGINS: "http://localhost:3000,http://localhost:5173"
    ports:
      - "8080:8080"
    volumes:
      - ./uploads:/app/uploads

  frontend:
    build:
      context: ../repair-flow-frontend
      dockerfile: Dockerfile
    container_name: web-repairflow-local
    depends_on:
      - backend
    ports:
      - "3000:80"


volumes:
  pgdata-local:
